[package]
name = "mini_tiktok_auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = { version = "0.11.6", default-features = false }
redis = { version = "0.22.2", default-features = false, features = [] }
tonic = { version = "0.8.3", default-features = false, features = ["transport", "codegen", "prost"] }

[build-dependencies]
tonic-build = "0.8.4"
