apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        sidecar.jaegertracing.io/inject: 'true'
    labels:
        app: paraparty-xiaobin
    name: bawling-minidouyin-auth
    namespace: bawling-minidouyin-auth
spec:
    selector:
        matchLabels:
            name: bawling-minidouyin-auth
    template:
        metadata:
            labels:
                app: bawling-minidouyin-auth
                branch: dev
                version: ${BUILD_NUMBER}-${CI_COMMIT_ID}
                name: bawling-minidouyin-auth
                dream-app: bawling-minidouyin-auth
                dream-unit: bawling-minidouyin-auth
        spec:
            imagePullSecrets:
                -   name: regcred
            containers:
                -   image: ${IMAGE}
                    imagePullPolicy: IfNotPresent
                    name: bawling-minidouyin-auth
                    readinessProbe:
                        exec:
                            command: ["/bin/grpc_health_probe", "-addr=:14514"]
                        initialDelaySeconds: 5
                        periodSeconds: 5
                        successThreshold: 2
                    livenessProbe:
                        failureThreshold: 3
                        exec:
                            command: ["/bin/grpc_health_probe", "-addr=:14514"]
                        initialDelaySeconds: 10
                        periodSeconds: 10
                        timeoutSeconds: 1
                    envFrom:
                        -   configMapRef:
                                name: env-config
                        -   configMapRef:
                                name: config
                    ports:
                        -   containerPort: 14514
            terminationGracePeriodSeconds: 30